/*
SQLyog Ultimate v12.5.1 (64 bit)
MySQL - 10.4.20-MariaDB : Database - db_blog2
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`db_blog2` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `db_blog2`;

/*Table structure for table `categories` */

DROP TABLE IF EXISTS `categories`;

CREATE TABLE `categories` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `categories_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `categories` */

insert  into `categories`(`id`,`name`,`slug`,`created_at`,`updated_at`) values 
(1,'Web Programming','web-programming','2021-10-11 11:34:41','2021-10-11 11:34:41'),
(2,'Web Design','web-design','2021-10-11 11:34:41','2021-10-11 11:34:41'),
(3,'Personal','personal','2021-10-11 11:34:42','2021-10-11 11:34:42');

/*Table structure for table `failed_jobs` */

DROP TABLE IF EXISTS `failed_jobs`;

CREATE TABLE `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `failed_jobs` */

/*Table structure for table `migrations` */

DROP TABLE IF EXISTS `migrations`;

CREATE TABLE `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `migrations` */

insert  into `migrations`(`id`,`migration`,`batch`) values 
(1,'2014_10_12_000000_create_users_table',1),
(2,'2014_10_12_100000_create_password_resets_table',1),
(3,'2019_08_19_000000_create_failed_jobs_table',1),
(4,'2019_12_14_000001_create_personal_access_tokens_table',1),
(5,'2021_10_06_231602_create_posts_table',1),
(6,'2021_10_06_235653_create_categories_table',1),
(7,'2021_10_12_064114_add_is_admin_to_users_table',2);

/*Table structure for table `password_resets` */

DROP TABLE IF EXISTS `password_resets`;

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `password_resets` */

/*Table structure for table `personal_access_tokens` */

DROP TABLE IF EXISTS `personal_access_tokens`;

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `personal_access_tokens` */

/*Table structure for table `posts` */

DROP TABLE IF EXISTS `posts`;

CREATE TABLE `posts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `category_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `published_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `posts` */

insert  into `posts`(`id`,`category_id`,`user_id`,`title`,`slug`,`image`,`excerpt`,`body`,`published_at`,`created_at`,`updated_at`) values 
(1,1,3,'Velit deleniti dolores aspernatur at similique.','facere-aut-quam-est-ut-et',NULL,'Debitis voluptas cumque sit natus. Voluptas odit molestiae nesciunt et alias corporis aperiam. Voluptatem ut et odio ad recusandae reiciendis voluptate. Quae qui sunt quod non. Nesciunt sequi ipsam aut accusantium ullam molestias.','<p>Facilis eum minima aut omnis voluptatem qui. Iste itaque consequatur tempora neque et quia. Ut ut facilis nihil veniam doloribus ut. Commodi provident autem accusantium non corporis.</p><p>Veniam enim ut consequatur qui inventore illo id. Aperiam rerum illum quasi voluptatum corporis quidem voluptatem. Quam neque temporibus aliquid. Corporis laudantium sint laborum illum facere et.</p><p>Distinctio eos similique nihil voluptas omnis. Et quaerat sunt itaque saepe recusandae. Sunt quo architecto tenetur id eveniet. Esse velit accusantium ratione beatae expedita sit sed. Quis laborum sequi et nulla ea quos.</p><p>Quisquam iure possimus modi quia sunt. Velit quia voluptatum repellendus reprehenderit et. A sapiente ipsum perferendis et et quis labore. Earum velit aut inventore quibusdam aliquam.</p><p>Facere quam aliquam voluptatum et architecto dignissimos eaque. Sit impedit sed sunt eos.</p><p>Magni dolores laboriosam quo accusamus aperiam libero sint. Laudantium aut consequatur earum pariatur veniam. Odio neque earum perferendis delectus.</p><p>Rerum dignissimos quod commodi repellat et libero vero. Ab nulla voluptas pariatur animi. Dignissimos maiores dolor nisi et quis in placeat. Mollitia ea quos veniam cum ut.</p><p>Ex vel sunt distinctio corrupti perferendis. Quia voluptates aliquid quis pariatur corporis. Quae aut molestiae commodi nobis voluptatem est voluptas. Possimus tenetur delectus adipisci et tempora nesciunt occaecati molestias.</p><p>Saepe odit veritatis nisi cupiditate. Excepturi unde minima rerum neque facere sequi molestias magnam. Non et cum totam labore.</p><p>Id est unde reiciendis numquam adipisci tenetur. Distinctio quos non ex officiis. Et distinctio incidunt voluptatem consequatur at eos vel veritatis. Est est est aut sit.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(2,2,3,'Vero alias deleniti itaque.','sed-minima-omnis-impedit-optio',NULL,'At perspiciatis ut quia qui. Quis repudiandae optio et ullam laudantium consequatur consectetur. Tempore et eveniet voluptas facilis nam. Autem tenetur sint voluptas error expedita et.','<p>Occaecati sint et aut nihil veritatis eos. Id quia quia veritatis esse dolor consequatur ea reiciendis. Voluptatem minus officia eos mollitia veritatis aut. Inventore similique illum fugiat quis. Consectetur quo id itaque voluptas architecto et vero.</p><p>Incidunt nisi reiciendis ex natus ut et qui. Sequi nulla sequi odit pariatur. Quis incidunt nobis saepe consequatur tempora assumenda aspernatur. Et aliquid voluptas saepe doloribus facilis voluptas voluptatem vel.</p><p>Ex suscipit officiis consequatur hic blanditiis provident. Ullam saepe sed totam est quae. Qui esse nesciunt illum odit quo dicta mollitia. Libero et dolore officiis cumque ea tenetur facilis esse. Iusto nisi maxime iure rerum.</p><p>Suscipit ut magnam omnis ut eum at. Ratione facere consequatur dolores eaque libero recusandae aut. Fuga facere consequatur repellendus amet sint nobis praesentium. Aspernatur voluptatem commodi natus libero ea eos culpa.</p><p>Temporibus eligendi in quia accusantium necessitatibus repellat laborum. Dolorem non totam eos aspernatur. Autem eos exercitationem rerum nisi pariatur quia. Temporibus unde quam nobis eos. Molestiae quo voluptatem nihil est.</p><p>Rerum odio autem itaque minus. Qui debitis aut optio ab impedit possimus rerum sit. Architecto dolores ea modi cumque. Aliquid esse qui consequatur praesentium error sit quis.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(3,2,2,'Suscipit optio.','voluptates-labore-laudantium-non-ea-at',NULL,'Neque molestias esse illum. Voluptas nemo facere aliquam deleniti voluptate quae eum. Qui quo sit qui. Ut sint sapiente sed non.','<p>Omnis sed eveniet ipsam et placeat et dolor. Et at enim impedit pariatur. Adipisci autem aliquid veniam. Exercitationem sint eius beatae enim mollitia commodi.</p><p>Non vitae sequi commodi reiciendis. Culpa molestias sint commodi hic voluptate. Quae modi est vel alias adipisci provident. Ducimus similique voluptatem maiores qui cumque.</p><p>Molestias ullam ut iure. Cupiditate sit ut molestiae minus quam. Qui culpa deserunt saepe et. Quidem omnis quia dolores deleniti.</p><p>Praesentium deleniti et ut qui qui repudiandae autem. Consequatur soluta ut deleniti libero placeat tempore cupiditate. Saepe id optio voluptatum consectetur laudantium quas. Consectetur consequatur recusandae ex sequi aut.</p><p>Ipsum quaerat tempore ipsam. Voluptas voluptatibus sunt sit ex. Beatae ea omnis modi quia fuga. Doloremque cumque autem inventore delectus vero illo.</p><p>Qui nemo modi expedita id nostrum aliquid atque qui. Aliquam quisquam qui repudiandae doloremque. Quo quaerat et quos aut mollitia qui eaque. Autem sed et aut quidem ut temporibus.</p><p>Autem eius magni et quo incidunt rerum in. Est esse est illo recusandae ut ducimus. Similique vero ullam laboriosam quo consequatur.</p><p>Ut nostrum dicta assumenda quasi in. Suscipit eligendi in aspernatur odio. Eius molestiae error et ducimus magnam. Magnam excepturi qui dolores fuga ab ut occaecati.</p><p>Voluptas magnam quia quisquam omnis. Laborum iure incidunt mollitia eaque delectus quo quibusdam. Voluptates repudiandae deleniti non molestiae non id.</p><p>Dolore voluptates et facere quo sit vel et. Blanditiis enim repellendus dolor omnis et nihil. Consectetur omnis perspiciatis et vel. Consequatur nemo tenetur dolorem nostrum accusamus.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(4,1,1,'Doloremque illo.','sint-architecto-sed-esse-porro-ab-dicta',NULL,'Aut cumque porro pariatur illum esse voluptas ad. Nisi porro aliquam aut. Necessitatibus corrupti impedit odit. At rem aliquid facilis voluptatem possimus.','<p>Atque repudiandae numquam eum consequuntur suscipit. Doloribus consequatur porro et rem. Iste officiis et et ut maxime.</p><p>Similique rem asperiores ut ut. Et est quas rerum excepturi. Et harum dolor et perferendis. Repudiandae voluptatem tempora sit.</p><p>Non ea eius veniam sit voluptatem eum illo. Alias ex et nihil atque eligendi. Facere voluptatem rerum corrupti at dolor.</p><p>Eligendi est natus autem explicabo assumenda. Quas harum optio fugiat aspernatur voluptates cum. Ipsum harum odio et ea laboriosam adipisci quisquam.</p><p>Labore iure nemo delectus vitae. Veniam ut dolorum rerum a fugiat et exercitationem. Hic neque iure et fugiat. Atque eaque quis tempora laborum. Illum sit beatae odio voluptate deserunt dolor cumque beatae.</p><p>Aut similique optio voluptatem. Delectus saepe et tempore quasi iure facilis. Dolorem debitis qui natus dolorem beatae voluptate blanditiis. Et officia saepe et amet harum et aut rem.</p><p>Repellat beatae at quod itaque. Aut nobis provident quo explicabo atque fugiat. Nesciunt corporis commodi distinctio aut ipsum ullam molestiae voluptatem. Aliquid ea quo voluptates provident architecto quibusdam tenetur.</p><p>Explicabo neque possimus sunt ut itaque. Occaecati doloribus ut totam suscipit repellat et accusantium. Natus reiciendis inventore blanditiis cumque quibusdam quisquam.</p><p>Facere voluptatibus quis quia a laudantium maxime inventore. Aliquid cumque aut fugiat corporis exercitationem quia quas libero. Earum deleniti earum autem aliquam nam. Velit enim ut qui voluptas. Deleniti nihil suscipit quidem consequuntur officia consectetur et.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(5,2,3,'Consequuntur deleniti necessitatibus tenetur nobis amet.','magni-veritatis-omnis-ut-facere',NULL,'Reiciendis hic quia nulla non mollitia laboriosam. Rerum consequuntur ut voluptatem inventore. Deleniti enim culpa nobis ad molestiae sit. Aspernatur voluptatum ducimus consequatur dolorum.','<p>Eaque quis autem dolore et. Dolores animi harum nisi eius reprehenderit laboriosam est. Et consequuntur debitis et eum ea. Tenetur harum explicabo aut ipsam ducimus voluptatem aspernatur.</p><p>Aut quae accusantium est assumenda eligendi. Totam iste aut deleniti soluta perspiciatis. Possimus a odio ipsa atque ut delectus fugit. Doloribus quibusdam labore cupiditate molestiae.</p><p>Sit rem illo unde ipsa. Autem consequatur tempore debitis architecto. Atque eum doloremque quaerat quia voluptas fugiat laborum. Quia ut odit est id aspernatur soluta et voluptatibus.</p><p>Quos assumenda occaecati ut ipsa sequi nostrum quis. Saepe ipsa qui dolores beatae. Quia consequatur quia odio nostrum non. Vitae omnis eligendi non tempore. Non voluptas est commodi non et.</p><p>Autem sunt consequatur fugiat amet qui. Hic fuga laboriosam voluptatem facilis libero aut perferendis. Voluptatum quia ut animi voluptas vitae.</p><p>Eos qui omnis dolor. Accusamus quam unde possimus. Quis sed eum adipisci aut omnis ducimus animi.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(6,1,1,'Quos rerum praesentium inventore consectetur aut nihil.','ea-voluptates-non-in-sed-esse-ex',NULL,'Officiis recusandae ipsum repellat libero recusandae molestiae ipsum. Soluta quos dolorem eos ad consequatur qui laboriosam.','<p>Inventore odio neque error at. Tenetur omnis ab sint excepturi vero et unde neque. Corporis ullam debitis ducimus velit.</p><p>Voluptas non repudiandae maxime incidunt. Odit nulla ad possimus sequi optio. Temporibus ut veniam commodi qui enim qui.</p><p>Aut autem consequuntur cum atque aut praesentium consectetur magnam. Culpa reiciendis cupiditate veniam sapiente qui debitis error quod. Et error omnis nostrum natus quia aut optio.</p><p>Vel soluta odit ut rerum. Quia tenetur dolorem ut. Enim unde assumenda ut ipsa dolores quis.</p><p>Quae quo expedita iste voluptas. Vel quam dolorem sit tenetur porro. Autem fuga rem eveniet.</p><p>Ratione consequatur doloremque et reiciendis et. Itaque quas aspernatur inventore nihil. Totam a illo sed ut ut. Ut exercitationem recusandae accusamus autem.</p><p>Laborum accusamus expedita debitis aliquid et. Ut similique corrupti qui voluptatum sint et quod ea. Laborum et sit aut voluptatum. Nisi amet sequi aut maxime eos aut.</p><p>Inventore eius optio sapiente nemo nam fuga et. Ea unde assumenda id et debitis quibusdam aperiam laborum. Impedit sequi earum ea unde aut id molestias quia.</p><p>Eum dolorum nesciunt nisi eum quam iusto ad. Est eos officia temporibus asperiores magnam vel quam.</p><p>Ea qui et ipsam repellat qui dolorum. Non pariatur molestias cupiditate totam et. Amet fugit laudantium consequatur unde occaecati eum.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(7,2,2,'Maiores saepe odit.','ratione-excepturi-sed-qui-veniam-et-libero-adipisci',NULL,'Ratione laudantium in dolor maxime minus ratione. Qui rerum illum aut odit soluta. Voluptas dolorem nostrum ipsam sed esse sed voluptatem nam.','<p>Voluptas fugit voluptatem enim aut omnis in et. Error qui non officiis maiores itaque ipsa. Dolor nisi hic voluptatum hic officiis fugit. Enim cumque iusto eos quis ut inventore quisquam.</p><p>Quia eum vero numquam voluptatibus minus dolore voluptatem odit. Amet voluptatem rerum quisquam nam.</p><p>Repudiandae totam error labore necessitatibus enim odio. Maxime vel nihil sint et rerum. Occaecati iure doloribus et rem cum et similique corporis. Eum minima recusandae omnis voluptate dolores debitis et.</p><p>Repellat aliquid quibusdam reiciendis est sed et. Architecto debitis non sint et quidem aliquid illo cumque. Aliquam similique sunt et consequatur quaerat. Inventore et minima fuga voluptatum aut.</p><p>Et temporibus aut corporis. Alias esse sapiente fuga ab fuga eligendi nesciunt. Sed ad quam aspernatur libero. Est adipisci sed itaque eius ipsum voluptatem et.</p><p>Quae consequatur sapiente suscipit atque voluptatem ipsam. Dolor culpa et aliquam optio et non culpa. Unde labore harum et velit corrupti.</p><p>Sequi eveniet commodi dignissimos sit occaecati hic est. Et voluptatem et ipsum voluptatem sint voluptas consequatur. Adipisci et voluptatem velit corrupti quibusdam.</p><p>Voluptates quidem ex numquam voluptatem. Reprehenderit consectetur delectus nesciunt et iste sapiente excepturi. Reprehenderit blanditiis ut ut libero facilis. Quam assumenda accusantium beatae libero sit iste.</p><p>Consequuntur aut qui dolorem consectetur corporis eum ullam veniam. Possimus nihil dolor deserunt dolor architecto maxime. Aut minus omnis quia nesciunt ex. Occaecati et molestias fugit excepturi qui esse vel.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(8,1,3,'A distinctio explicabo corrupti.','est-iusto-quia-suscipit-iste',NULL,'Aut quo nobis nam alias. Sit sunt dicta dignissimos maiores quisquam iure dolorem. Aut rerum repellat cupiditate earum ea.','<p>Et est optio aut ut voluptatem et. Omnis mollitia in non qui. Dolor delectus nihil illum id architecto. Nemo ullam animi incidunt aliquam dolores sint. Quia aliquam ratione iusto sed eligendi ea.</p><p>Adipisci et dolorum voluptas. Sunt commodi unde ratione. Officiis numquam eum quidem doloremque deserunt autem tenetur delectus. Omnis occaecati quia ad ut ad a eligendi.</p><p>Dolor omnis delectus cupiditate. Laborum illum qui sed neque. Quibusdam qui odit rerum et. Placeat et nostrum distinctio velit laboriosam optio.</p><p>Corrupti rerum consequatur odio aspernatur neque aspernatur quia. Quis et recusandae reiciendis voluptatum unde. Ratione quod aliquam ut mollitia esse molestias dolor. Iusto aut delectus architecto aperiam et eos ea.</p><p>Aliquam et quas doloribus optio impedit quis. Quia totam laudantium nam quia dolorem reprehenderit error. Omnis deleniti animi deleniti et quod numquam id.</p><p>Molestiae ullam tenetur ut repudiandae reiciendis. In dolor excepturi est voluptates. Adipisci sint deleniti sed. Autem tenetur excepturi nostrum eligendi iusto sit sunt. Autem velit asperiores doloribus facilis.</p><p>Rerum optio corrupti nemo quis consectetur in dignissimos. Voluptate vitae optio pariatur molestiae veritatis. Nihil eos autem sequi consequatur accusamus omnis.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(9,1,1,'Consequatur sunt quibusdam quam iusto.','voluptates-voluptatem-dolorem-fugiat-eum-ea-odit',NULL,'Ut qui fugit dolores odio. Eos excepturi debitis esse aperiam exercitationem eveniet. Vel totam dicta iusto occaecati amet voluptate. Dolorum itaque eos distinctio non sit quo aspernatur.','<p>Laborum repellat vel libero enim et omnis. Veniam asperiores et et non omnis et. Rerum magni nobis enim enim. Id mollitia ut et magni facilis ut.</p><p>Consectetur distinctio aliquam veritatis dolores. Est ullam et dolores maiores. Id quam voluptatem explicabo exercitationem voluptatem sint. Doloribus labore sint sit adipisci vero magnam enim.</p><p>Reprehenderit fuga quia molestiae recusandae occaecati voluptatem illo est. Similique sit qui optio voluptatum aut nisi ducimus. Nemo et dolores ea non sed. Praesentium cum voluptate occaecati dicta.</p><p>Amet qui vitae laudantium dolore qui dolores eos. Placeat modi qui ipsum incidunt temporibus est. Quo possimus eum ea a.</p><p>Commodi quos error similique provident voluptatem. Facere voluptatum fuga neque. Illo repellat illo in sequi ea ut reprehenderit et.</p><p>Beatae magni reprehenderit ipsum quae quia cum accusantium. Ut qui in deserunt minima ea et enim. Dignissimos vel corrupti omnis culpa iusto rem.</p><p>Eaque itaque aut omnis assumenda dolorem eveniet quis. Quae repellat magnam rem aliquam nobis dignissimos modi dicta. Qui qui facilis ducimus earum et esse accusamus.</p><p>Libero explicabo quibusdam dicta explicabo eveniet. Harum nesciunt odit dolorum autem iure. Numquam consequuntur optio praesentium voluptate harum sit non molestias. Nam nisi incidunt est ea.</p><p>Sed nisi iste iure facere est. Recusandae aliquid dicta dolor ad. Temporibus vero velit et tenetur sit.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(10,1,1,'Dolorem pariatur commodi corrupti ea voluptas id.','cumque-quisquam-accusantium-repudiandae-rerum-aut-voluptas-sequi-corporis',NULL,'Quibusdam non qui fuga reiciendis quis est. Molestiae aut fugit voluptates autem. Nisi dolorum omnis eveniet. Voluptas hic unde nemo voluptas est ipsum.','<p>Molestias ut repellat sint tempore nam ducimus. Facilis repudiandae earum possimus est aspernatur. Eligendi fugiat iste maiores.</p><p>Provident earum sit est. Qui laborum explicabo eveniet labore ut eaque. Cum amet perspiciatis est voluptates quam.</p><p>Rerum deleniti aut recusandae doloremque animi optio. Quam voluptatem delectus consequuntur.</p><p>Sed sed commodi pariatur dicta esse ex ullam vitae. Ipsa provident omnis tempore reiciendis ut veritatis debitis. Quos quo qui tempora aut iusto voluptatem.</p><p>Aut eveniet sed vel illum earum aut excepturi. Consequatur repellat exercitationem saepe tempora. Et totam hic tenetur quis. Aperiam ex est expedita quis expedita qui.</p><p>Laborum dicta debitis qui non. Facilis voluptatum debitis porro delectus voluptatum nemo. Non quasi autem possimus ullam. Quos repellendus earum itaque minus.</p><p>Laudantium facere optio optio sit rerum. Quas placeat numquam sed. Velit sed dolor sint omnis consequatur.</p><p>Consequuntur est distinctio et dolor a dolorem et. Qui rerum veritatis ipsam tempora aspernatur est voluptatem. Excepturi sit quia sunt qui. Esse eum accusantium est ab. Provident qui cum dolore dicta.</p><p>Fugiat perspiciatis qui hic adipisci reiciendis iste et. Quod ea rem aliquid omnis reiciendis. Voluptates quidem ratione molestiae illum molestiae non tempora odio. Eos velit eaque dolores iste dolore.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(11,1,3,'Magni mollitia iste.','eaque-suscipit-modi-enim-suscipit-est-odit',NULL,'Quia molestiae eius harum ullam animi dolores aliquam corrupti. Et id velit neque quod aliquid velit aut. Adipisci voluptate deleniti numquam voluptatem voluptatibus ducimus ut quas. At soluta praesentium dolores iste maxime ullam voluptatum.','<p>Error qui nobis quo architecto. Atque assumenda ipsam vitae nobis aut libero est. Voluptates ipsa tempora ratione qui accusantium numquam perferendis.</p><p>Voluptatem laudantium ipsam doloribus quas aliquid. Maiores molestiae natus et vel sed. Eveniet nobis et consectetur rerum earum.</p><p>Iusto recusandae laborum itaque voluptas officiis. Mollitia molestiae veritatis numquam rerum. Ipsa cupiditate dolorem quis velit.</p><p>Soluta voluptatem suscipit ea atque veniam dolores et. Minus nihil voluptate et sit autem officia qui. Laboriosam quis autem qui natus eaque quasi enim. Libero saepe qui voluptate libero quas qui ut.</p><p>Qui aut in dolores deleniti ratione repellendus. Dignissimos nisi fuga quisquam et ut iure dolore. Incidunt enim rerum repudiandae iste beatae. Qui sed ipsum reiciendis nihil architecto. Eligendi perspiciatis atque distinctio est sed.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(12,2,3,'Architecto quas ea repellat veniam est.','maiores-impedit-sed-eaque-itaque-et-mollitia-ad',NULL,'Sit repellendus maiores provident fugiat sint ut aut. Harum eos accusamus dignissimos atque sit aut. Beatae quidem inventore accusantium aliquid sed accusantium ipsa. Itaque quia voluptates et vel ab sit odio. Est eaque ullam explicabo id deleniti.','<p>Unde id sunt quam qui fugit neque maxime. Commodi libero ut incidunt voluptatem quis tenetur. In voluptatem quos quo quia vel.</p><p>Ratione dolor a quos molestiae totam quia. Porro enim soluta ducimus quis accusamus quibusdam itaque ut. Vel quasi ducimus dicta.</p><p>Et rerum tempora voluptatem placeat quo quo sapiente. Tempora ipsa in dolores voluptatibus. Dolore quam fugit neque nihil sunt officiis minus dolorem. Perferendis sint ab repudiandae alias omnis ea rerum.</p><p>Iure accusamus dolorem quaerat qui blanditiis fugit tenetur. Eaque deleniti assumenda non aut itaque enim. Pariatur saepe asperiores deleniti unde.</p><p>Ad et praesentium et. Quisquam voluptatum voluptatum ut eius est ipsam expedita. Voluptas ipsum velit aut et sed quia ducimus harum. Ex ut laudantium et suscipit dolorem at.</p><p>Cupiditate sed praesentium animi ut veritatis. Ab fugit consequuntur numquam exercitationem non rem reiciendis est. Et earum architecto tenetur.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(13,1,2,'Eos aut dolore saepe velit quos quo.','excepturi-est-dolor-veniam-nostrum-eius-qui-officiis-et',NULL,'At blanditiis asperiores recusandae ea quo sit eum. Quas odio sit labore eveniet dolores placeat et. Voluptatem odio et quia perferendis.','<p>At vitae facilis qui consequuntur laudantium ipsa. Qui deserunt doloremque neque quis occaecati dolorum earum. Et sit quia aperiam molestiae et quia deleniti. Sint et possimus consequatur laboriosam veritatis et rerum.</p><p>Necessitatibus earum ex reiciendis dolores. Iste sit soluta assumenda tempora. Et autem dolorem ea deleniti facilis non consequuntur et.</p><p>Dolor dolor at doloribus. Autem nulla ea quas sed. Consequatur nisi quibusdam animi quis corporis nobis.</p><p>Excepturi quia odio et quaerat veniam nemo. Et ratione quisquam similique et. Possimus necessitatibus eaque harum voluptas et. Numquam rerum iure nostrum nemo eos voluptatem.</p><p>Recusandae velit ex quasi sint qui. Exercitationem eveniet deserunt et ut aut beatae facere. Aut quia voluptas similique. Accusamus id aspernatur cupiditate odio a laborum.</p><p>Illo eligendi sit modi et. Quos ducimus repellat atque doloremque quos quidem autem. Pariatur temporibus ipsa vitae deleniti dignissimos consequatur.</p><p>Vel consequuntur et molestias officia eum. Voluptatibus ea velit rerum est.</p><p>Dicta et voluptatibus enim dignissimos soluta. Cum repellat earum consectetur accusamus. Voluptas nisi sed porro. Sequi pariatur nulla mollitia.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(14,1,2,'Et magni excepturi.','ut-aspernatur-vel-blanditiis-non-qui-sed-perspiciatis',NULL,'Eius sunt eum adipisci aut rerum. Possimus aut eaque quod dignissimos ullam consequuntur sunt. Vel id debitis debitis sunt. Nemo nostrum ut debitis corporis sint enim doloribus sunt.','<p>Ratione sit ullam quo vitae. Quis quia eum eius consequuntur ab assumenda excepturi. Distinctio delectus maxime quo et. Eos voluptatem placeat sint amet cumque.</p><p>Inventore magnam placeat impedit ullam. Est aperiam non commodi. Dolorem et expedita nesciunt beatae deserunt sequi ut. Est sunt est aut optio.</p><p>Voluptatem soluta impedit cumque et. Laboriosam neque corporis omnis eos. Quidem nulla exercitationem sit vero. Labore doloremque nihil ut tenetur quos. Excepturi voluptas rem sunt qui sit soluta culpa.</p><p>Dignissimos iure consequuntur corporis eum quos voluptas est distinctio. Tempore sint est maxime corporis a qui ipsa reiciendis.</p><p>Numquam non a in molestias voluptatibus consequuntur quibusdam. Aut voluptas rerum asperiores numquam. Ut facere laudantium quam architecto. Iste sed adipisci ut impedit ut aut consequuntur quia.</p><p>Sit quia dolore ex in dolor. Ducimus quis sit eos. Possimus harum suscipit tenetur asperiores accusantium. Est ut officia necessitatibus dolorem eos.</p><p>Recusandae rerum adipisci fuga qui et. Ut tenetur vel veniam voluptate nesciunt. Animi consectetur quisquam dolor magnam molestiae commodi expedita.</p><p>Consequatur voluptatem atque reiciendis. Aut a aliquid esse sed eos. Et harum esse beatae consequatur rerum deserunt praesentium repudiandae. Harum reiciendis id doloremque quia ad.</p><p>Debitis voluptas exercitationem magni et sit. Minus exercitationem quos quo. Consequatur eveniet pariatur aut quo veniam quis sapiente.</p><p>Mollitia iste tempore inventore deserunt molestias possimus. Molestias quidem nihil aspernatur qui. Provident inventore et autem officia atque. Ratione porro doloremque enim et ipsum voluptas.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(15,2,2,'Quia saepe sit et.','nobis-sequi-consequatur-enim-minus-et-dicta',NULL,'Iusto culpa qui omnis temporibus deleniti aspernatur non. Dolor molestiae ipsum eaque alias. Non perferendis enim culpa id dolores animi. Praesentium rem voluptas fuga minus totam aut.','<p>Et quia quia alias. Saepe explicabo ea ullam voluptatum qui.</p><p>Et et id commodi harum. Ea maxime molestiae dolores ipsum. Eveniet et expedita laudantium. Voluptas vitae iste ex rerum voluptas.</p><p>Tempora id enim corporis quia. Reprehenderit et eum ut optio qui voluptatum reiciendis. Quis dolor ullam officiis ab quaerat debitis fugit.</p><p>Nihil voluptate nulla similique assumenda quidem eum veritatis assumenda. Dolorem rem soluta sunt quo laborum ea id. Ea error temporibus illum dolor reiciendis voluptatem.</p><p>Id nostrum laboriosam accusantium. Nisi fugit natus ex rerum quam velit.</p><p>Quis quo quo rem magnam atque. Officiis vel unde minus et reprehenderit. Molestiae rem voluptatibus eligendi dolores. Ut maiores sit enim.</p><p>Et aut enim est voluptatem similique sequi. Dolorem voluptatibus sit ut id est et. Vel quidem laborum delectus. Enim doloremque voluptate nesciunt facilis adipisci aut.</p><p>Sit et impedit nemo cum. Doloribus molestias quia id dolor temporibus est.</p><p>Distinctio sed necessitatibus alias magni itaque rerum adipisci. Voluptates provident repellendus aperiam voluptatem. Dolores asperiores corrupti voluptatum sunt. Dicta dolore et quasi asperiores laudantium. Perspiciatis officia voluptas rerum et quibusdam aut autem.</p><p>Consequatur architecto quibusdam sit voluptatum qui. Cum et non aliquam praesentium facilis aut. Omnis quos consequatur enim quaerat voluptatibus.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(16,2,3,'Et molestias ut non.','blanditiis-voluptas-magni-eveniet-officia-ea-facilis-debitis',NULL,'Tenetur sint aut commodi qui. Possimus totam sint unde. Temporibus quisquam ratione beatae totam.','<p>Nihil voluptas omnis laborum modi. Iste sit et assumenda quia. Pariatur repellendus quae sed libero non quam neque eaque.</p><p>Veniam et odit veritatis dolorem expedita. Consequuntur delectus voluptas distinctio omnis adipisci sunt dolore. Vel similique placeat et.</p><p>Est enim aliquid quo nisi. Minus et et est.</p><p>Debitis ut possimus autem officia quia et dolores. Minima soluta aut est at. Debitis veniam culpa nulla optio doloremque.</p><p>Rerum repellendus est ab fugit. Blanditiis praesentium ex ea repellendus laborum. Id aliquid porro sit aspernatur quidem in. Asperiores consequatur dolor sed. Nisi ut culpa quas dolorem eum.</p><p>Modi corporis quae aut et voluptas. Qui sit quo autem debitis in. Possimus quisquam fuga ex quidem. Repellat eligendi voluptas illum corporis. Aut culpa sequi modi repudiandae voluptas recusandae nobis ducimus.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(17,2,1,'Optio numquam voluptate reiciendis molestias magni labore ipsam.','voluptatibus-est-aut-nulla-velit-consectetur-magnam-nam',NULL,'Ipsam enim occaecati veniam laboriosam accusamus ut dolore. Eveniet consequatur ut recusandae esse. Vel quis ut fugiat suscipit nemo sunt. Maxime voluptatem dolorem facere rem.','<p>Iure explicabo molestias cum sit perspiciatis. Quia sed corrupti tenetur vero itaque aspernatur dignissimos. Cum maiores quae facere ipsam et.</p><p>Nostrum itaque in omnis rerum hic et et. Ducimus et ab error voluptates officia distinctio nam dolorem. Accusamus vitae voluptas deserunt est. Ratione dolorem voluptatem iusto.</p><p>Labore sapiente praesentium numquam sequi. Et esse quia et sed minima. Eos dolorum iusto tenetur quam beatae odit eum. Maiores dignissimos quia et rerum quam.</p><p>Sit eos laborum pariatur porro dolores enim. Aliquam architecto et id ab facere doloremque tenetur. Ut voluptas dolor voluptas sit aut facere ex. Tempora perferendis provident eum libero omnis.</p><p>Recusandae soluta reprehenderit fugit aperiam consectetur et quia. Nulla eius sint et et. Soluta aut sit asperiores aut possimus nam tempora. Voluptas ipsam itaque sed doloribus doloribus dolor.</p><p>Ea temporibus velit quod fugiat officia rerum maiores. Est voluptatibus ea ad nihil natus. Iste velit voluptatem iure voluptates quas iste enim architecto.</p><p>Expedita inventore dolorem iste vel. Occaecati voluptatem veritatis est non optio et quaerat. Non similique aperiam accusamus quasi.</p><p>Velit consequatur quod repellendus iure vero. Maiores iusto natus unde ut eaque. Nesciunt quia eveniet quo voluptas corporis nisi officiis.</p><p>Autem rerum debitis nostrum dignissimos velit aperiam. Ut culpa quo modi debitis. Atque quos nulla hic ea et et. Ut dolores molestias blanditiis et quia maiores vel.</p><p>Odit et accusantium dolorum et enim et harum. Eos repellat quia aut dolor qui culpa. Qui nisi quo non possimus tempore soluta in recusandae. Est enim assumenda autem officiis accusamus.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(18,2,3,'Ab velit nisi aut eum nobis vel tenetur.','tempore-dolore-ut-asperiores-provident-est-vel',NULL,'Cum aut soluta laboriosam illo eos. Ut quibusdam incidunt animi incidunt dolores dicta dicta. Suscipit ducimus est fugiat dolores quasi.','<p>Voluptatem praesentium voluptas natus illo. Velit consequatur illum voluptas velit odio. Possimus nesciunt et et at magni eligendi velit. Laudantium beatae qui ab iste odit aspernatur ut ipsum.</p><p>Voluptatem numquam quidem aut laudantium eveniet ex. Expedita quibusdam rerum nulla qui sed. Corrupti architecto at fugit ut ipsa aut.</p><p>Necessitatibus fugit aut sit sed non. Atque maxime repudiandae laudantium dolores modi. Corporis consectetur ullam et quos quis excepturi dolor non.</p><p>Sint praesentium aut aliquid recusandae id quis. Dignissimos officiis modi aut dolorem atque dolorum illum natus.</p><p>Architecto error sapiente iure aspernatur nulla. Placeat omnis quia odit quia omnis expedita molestiae. Quia id eum fugit omnis eum perspiciatis quos. Dolor quia maxime voluptatem rerum fuga est.</p><p>Officiis rem voluptatem et dolores. Deserunt exercitationem est aut harum. Hic omnis adipisci et sit praesentium velit reprehenderit.</p><p>Voluptatem numquam qui sit. Cumque quae expedita dignissimos nulla incidunt. Ea natus iste sed minima.</p>',NULL,'2021-10-11 11:34:42','2021-10-11 11:34:42'),
(19,1,2,'Cumque debitis.','facilis-dolores-aut-facere-voluptas',NULL,'Itaque aliquid occaecati et ut voluptatem. Enim reprehenderit minus aliquid. Ratione fuga consequatur dignissimos eum nesciunt. Sint aut voluptas soluta. Nisi velit accusantium minus nobis qui.','<p>Perferendis recusandae est consequuntur. Voluptatem dolores atque et nemo consequatur eum vel. At accusamus voluptatibus corrupti ea. Et quod et saepe sed distinctio. Maiores quidem cumque magni aut quam.</p><p>Est est quam quam aut. Quibusdam placeat quod sed est adipisci sint eum.</p><p>Ex distinctio amet repellat voluptas at autem sunt. Ex voluptatem alias ex aliquam. Qui nesciunt odit dolores tenetur aliquam neque soluta. Error hic minima dolorem id minus dicta reiciendis.</p><p>Impedit in est assumenda velit velit omnis in. Est sunt repellat facere eos est aliquam distinctio autem. Iure sit consequatur ducimus.</p><p>Voluptatem iusto ad eaque eligendi id suscipit corrupti. Eveniet reprehenderit aut eaque earum vero. Voluptatum blanditiis ut illo cupiditate vel.</p><p>Deleniti et assumenda repudiandae aut consectetur et. Nesciunt id aliquid optio aut. Quas nostrum sint qui saepe et consequatur.</p>',NULL,'2021-10-11 11:34:43','2021-10-11 11:34:43'),
(20,1,1,'Voluptatum tempora optio soluta.','ut-vero-doloribus-voluptatibus-soluta-ad',NULL,'Aut qui quibusdam amet delectus dolores. Aut facilis nostrum aut aut placeat. Ut amet fuga voluptas ut expedita.','<p>Animi qui voluptatem et quod laudantium aliquam. Eligendi sit exercitationem quod at sapiente qui. Impedit quam vel sit odit dolores.</p><p>Dolorum repellat dignissimos temporibus. Laborum reprehenderit non cum. Quo tenetur ea quia qui unde. Quia ducimus quia culpa fugiat sint at.</p><p>Praesentium numquam laboriosam exercitationem debitis quia repellendus recusandae. Labore omnis voluptatibus et aliquam fuga adipisci molestiae nihil. Nam alias nulla consequatur adipisci est et.</p><p>Corrupti repellat nulla tenetur qui eum laboriosam. Est officiis sapiente modi rerum incidunt natus vero. Qui ut pariatur eos et consectetur et.</p><p>Aspernatur eveniet quibusdam nostrum voluptatibus omnis perspiciatis. Quidem consequuntur commodi beatae qui aut magnam vero. Doloribus ut rerum dolore provident.</p><p>Culpa aut fuga assumenda repellat veniam accusantium quo. Quisquam vel iste error dolore commodi dolor impedit. Occaecati perferendis ipsam voluptas.</p>',NULL,'2021-10-11 11:34:43','2021-10-11 11:34:43'),
(23,1,2,'judul saja','judul-saja','post-images/lJlZWkbGrFwF1GeqETMUxFdWsRxukUKYBFeYwogB.png','testestes','<div>tes<br><br>tes<br><br>tes</div>',NULL,'2021-10-11 11:51:40','2021-10-11 13:21:33'),
(24,1,2,'judl','judl','post-images/fY3Nwg5230hjaOAc7annuGGYvE2HI9haSSVFcpF2.png','a','<div>a</div>',NULL,'2021-10-11 12:21:29','2021-10-11 13:21:47'),
(25,2,2,'aaaaaaaaaaaa','aaaaaaaaaaaa','post-images/xGbJ7PQX4v0HTPGKvPGuZelcZdkHD9i5FnS0FpLj.png','aaaaaaaaaa','<div>aaaaaaaaaa</div>',NULL,'2021-10-11 12:21:45','2021-10-11 13:21:57');

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_username_unique` (`username`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `users` */

insert  into `users`(`id`,`name`,`username`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`,`is_admin`) values 
(1,'Muhammad Padhilah','padhilahm','padhilahm@gmail.com',NULL,'$2y$10$wvkc.uGCJZmqNouu2C.hVenOrzuO2d3alnqQURv71BcbOdQsbwB5O',NULL,'2021-10-11 11:34:41','2021-10-11 11:34:41',1),
(2,'Maria Usada','saptono.tina','alaksita@example.com','2021-10-11 11:34:41','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi','5DMV973Y35VZCpFFD85UnNAMsN0ATbjJQg8Q6nWZZhX4MVqvlCQXuzxhlRcR','2021-10-11 11:34:41','2021-10-11 11:34:41',1),
(3,'Lukman Bakda Sihombing S.Pd','gyuliarti','lili29@example.org','2021-10-11 11:34:41','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi','TmZjGU7Al2','2021-10-11 11:34:41','2021-10-11 11:34:41',0),
(4,'Aisyah Usada','betania44','latika.widodo@example.net','2021-10-11 11:34:41','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi','21WTWEASrm','2021-10-11 11:34:41','2021-10-11 11:34:41',0);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
