/*
SQLyog Ultimate v12.5.1 (64 bit)
MySQL - 10.4.20-MariaDB : Database - db_blog2
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`db_blog2` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `db_blog2`;

/*Table structure for table `categories` */

DROP TABLE IF EXISTS `categories`;

CREATE TABLE `categories` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `categories_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `categories` */

insert  into `categories`(`id`,`name`,`slug`,`created_at`,`updated_at`) values 
(1,'Web Programming','web-programming','2021-10-08 13:14:18','2021-10-08 13:14:18'),
(2,'Web Design','web-design','2021-10-08 13:14:19','2021-10-08 13:14:19'),
(3,'Personal','personal','2021-10-08 13:14:19','2021-10-08 13:14:19');

/*Table structure for table `failed_jobs` */

DROP TABLE IF EXISTS `failed_jobs`;

CREATE TABLE `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `failed_jobs` */

/*Table structure for table `migrations` */

DROP TABLE IF EXISTS `migrations`;

CREATE TABLE `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `migrations` */

insert  into `migrations`(`id`,`migration`,`batch`) values 
(1,'2014_10_12_000000_create_users_table',1),
(2,'2014_10_12_100000_create_password_resets_table',1),
(3,'2019_08_19_000000_create_failed_jobs_table',1),
(4,'2019_12_14_000001_create_personal_access_tokens_table',1),
(5,'2021_10_06_231602_create_posts_table',1),
(6,'2021_10_06_235653_create_categories_table',1);

/*Table structure for table `password_resets` */

DROP TABLE IF EXISTS `password_resets`;

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `password_resets` */

/*Table structure for table `personal_access_tokens` */

DROP TABLE IF EXISTS `personal_access_tokens`;

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `personal_access_tokens` */

/*Table structure for table `posts` */

DROP TABLE IF EXISTS `posts`;

CREATE TABLE `posts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `category_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `published_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `posts` */

insert  into `posts`(`id`,`category_id`,`user_id`,`title`,`slug`,`excerpt`,`body`,`published_at`,`created_at`,`updated_at`) values 
(1,2,2,'Laboriosam facilis voluptatem in repellat nihil molestias odio harum.','inventore-autem-inventore-qui-eaque-vero-ut','Accusantium unde praesentium est quos et aut est. Deserunt incidunt modi sit assumenda nulla ex. Architecto cumque aspernatur qui sed. Et ipsam aperiam assumenda pariatur ullam.','<p>Ad consequatur ratione ea. Et quibusdam pariatur rerum soluta harum excepturi commodi. Earum rerum eaque sequi.</p><p>Quia ducimus ut officiis aut suscipit libero ea. Minima maxime enim et incidunt atque. Vel nam dolor quia distinctio amet molestiae. Temporibus quibusdam reprehenderit facere nihil tempora veniam.</p><p>Omnis eos quia assumenda modi eos. Commodi ut occaecati similique nisi omnis officiis adipisci distinctio. Inventore fugiat soluta et quam numquam. Labore distinctio sequi praesentium quasi aut ipsam incidunt tempore.</p><p>Beatae dolores sapiente est quia dolorem. Nobis consequatur saepe minus. Ut cum incidunt porro.</p><p>In ut et tempora magnam odit adipisci et. Dolores corporis laudantium et reprehenderit nesciunt aspernatur. Reprehenderit non qui est minima iure voluptatem. Modi quos autem veritatis qui voluptates.</p><p>Pariatur dolor consequatur dolorum. Sunt quos itaque dolores repellat. At error doloremque quae ipsa autem. Soluta quis autem blanditiis.</p><p>Praesentium ratione qui dolorem doloribus fugiat assumenda. Et similique a tenetur ut accusamus qui nobis. Quis aut laboriosam et sit. Voluptatem ut architecto molestias harum ea vel quam. Mollitia ut rerum et.</p><p>Debitis reprehenderit nemo voluptas iure iure enim. Odit quae minus possimus quia exercitationem. Explicabo quia qui consequatur. Vitae aut ea tempore qui corporis.</p><p>Voluptatem architecto veniam id est commodi quidem saepe cupiditate. In animi sed adipisci laudantium odio sint. Sed corporis voluptatem aliquam in nobis ducimus. Cumque sed quas praesentium cupiditate dicta aspernatur sit.</p><p>Culpa impedit occaecati ad laborum consequatur. A dolores provident provident quis ipsum. Ipsam sunt maiores non est. Ex quo voluptate unde reiciendis.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(2,1,1,'Culpa id voluptas nesciunt eius.','deserunt-illo-iste-molestiae-est-temporibus-autem','Autem ut quis quia minus. Porro perferendis et fugiat numquam sit consequatur beatae. Corrupti ipsa ex atque explicabo corrupti culpa.','<p>Sit earum deleniti dolor atque et. Fuga dolores facere aut at. Tempora dolores id consectetur inventore eos. Aliquam dolor ex id amet enim qui eum iste.</p><p>Deserunt sed fugit delectus ea sunt. Quia optio dolores dignissimos aut veniam ab qui. Consectetur exercitationem consequatur omnis deserunt officiis.</p><p>Voluptatem ducimus ad esse autem. Est minima quibusdam saepe rerum. Qui vero aut qui blanditiis nesciunt. Enim laboriosam accusantium qui est.</p><p>Distinctio facilis doloremque facilis ut quisquam cumque. Eum aut ut quae. Nostrum dolorum dolorem quo nihil est at.</p><p>Consequatur mollitia dolor ad voluptate reprehenderit et. Eum quo impedit atque consequatur temporibus. Labore est magnam exercitationem esse qui. Dolorum dicta totam praesentium laborum.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(3,2,1,'Et distinctio voluptas est cupiditate.','temporibus-autem-quasi-officiis-veniam-enim-rerum-aut','Ea accusamus a sit animi. Distinctio aliquid odio animi beatae ipsam architecto laudantium. Laborum aut expedita qui est. Tempore quibusdam quia soluta et sed voluptatibus.','<p>Explicabo libero quis nihil architecto. Sit esse minus voluptates et molestias reiciendis. Et omnis distinctio at saepe non officia aperiam quae. Eum quia ad occaecati eveniet sapiente.</p><p>Ipsa officia voluptatibus enim officia qui rerum. Quo dolore repudiandae non voluptas totam. Magni veniam ducimus minus quis. Sapiente quia voluptates qui consequatur officia.</p><p>Accusantium laborum voluptatem ducimus totam. Ut architecto qui magni autem non.</p><p>Placeat perspiciatis facere nesciunt autem quae. Est earum porro aut eaque. Officia fugiat cumque aperiam amet. Molestiae maiores laborum adipisci perspiciatis. Nam officiis asperiores repellat.</p><p>Expedita quae nemo totam vero autem. Et sed in dolores et consequuntur molestias. Nam placeat sit maxime facilis et.</p><p>Quia voluptate qui nesciunt cum quia qui quia nihil. Optio voluptas quia voluptates. Quia unde ea laboriosam est aut quidem.</p><p>Molestias ipsam eveniet consequatur aspernatur mollitia. Consequatur ipsum sed et natus ipsum doloribus laboriosam vitae. Ut et perspiciatis excepturi veniam quam repellat quia.</p><p>Quisquam minima id tenetur eum. Dolore tempora quidem harum atque.</p><p>Et assumenda exercitationem vitae illo delectus repellendus consequatur. Alias qui dolores vel ipsa recusandae ad. Sunt distinctio dolore enim repellat. Et et voluptatem sit fuga.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(4,2,2,'Fuga fugiat quas voluptas omnis recusandae.','voluptas-dolorem-officia-omnis-voluptate-optio','Totam aspernatur ut cupiditate perspiciatis alias. Ut illo ut vel dolores mollitia laudantium consequatur earum. Laborum qui quo sunt corporis doloremque.','<p>Est aperiam iusto inventore aspernatur fuga. Aliquam aut at voluptas amet nisi repellendus perspiciatis. Ea molestiae molestiae accusamus quia.</p><p>Nostrum molestias a autem facere error laboriosam. At amet ut sit aspernatur sapiente quaerat officia magni. Facere molestias qui id est nihil ipsa excepturi.</p><p>Qui qui debitis impedit quasi nulla quasi. Quisquam commodi alias fugiat quo magni rerum nisi. Nulla occaecati molestiae id consequuntur sit eveniet ducimus numquam. Doloremque ut nisi non qui labore et. Illo nihil quod voluptatem eligendi provident quod et.</p><p>Eaque fugiat et et et voluptatem. Voluptatem rerum alias sunt ratione illo praesentium voluptates. Libero ullam enim tempora iusto cum repudiandae. Tenetur expedita laboriosam numquam ex.</p><p>Ipsum officia alias unde sapiente mollitia quaerat. Totam qui beatae alias rerum facere alias. Omnis occaecati a quam quis.</p><p>Quia numquam eius repellat qui suscipit quia. Aut et iusto neque et veritatis dolor. Eum autem aut eaque error ut non omnis. Et doloremque in sint dolore nesciunt quam ut.</p><p>Expedita non eius totam ad voluptatem ratione ex. Voluptas laudantium consequatur consequatur deleniti illum quisquam.</p><p>Quae ea assumenda voluptatem maxime numquam. Laudantium itaque voluptatem reiciendis officiis in quo. Vel qui similique ullam placeat aspernatur non. Ab ea repellendus earum et culpa. Non repellat voluptate voluptas ad non laboriosam consectetur id.</p><p>Inventore consequatur quia enim sed. Nulla id dolores dolorum aut dicta aspernatur voluptatem. Mollitia nisi dolores est ut modi blanditiis iusto.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(5,1,3,'Totam voluptas quibusdam exercitationem laboriosam minima ipsam.','vel-ipsa-eos-nobis-qui-quis-numquam-ut-blanditiis','Doloremque molestias voluptas aliquid et recusandae enim ut. Praesentium velit unde quod illo molestiae omnis sed. Tempore voluptas dolorum suscipit in mollitia aperiam recusandae nisi. Reiciendis minus quaerat velit sed earum qui maiores aut.','<p>Modi fugit asperiores asperiores vero repudiandae eos. Harum omnis provident voluptate culpa reiciendis ut. Sint ea sint maxime repudiandae. Quia repellat voluptatum recusandae.</p><p>Dolores esse facilis quas adipisci. Suscipit et et qui consequatur officiis. In sequi eligendi consequatur consequatur neque dolore sint.</p><p>Hic velit dicta tenetur ut repellendus quidem ut. Eaque ea velit asperiores nihil sit. Est dolore quo porro quaerat consequuntur qui.</p><p>Quos blanditiis beatae itaque ullam. Perspiciatis atque nemo numquam sed iste qui. Et similique itaque et inventore quo aut. Expedita minus aut excepturi fuga modi repudiandae aliquam.</p><p>Nemo odio nihil ut a ea ab explicabo a. Repellendus numquam et recusandae quos. Velit dolorem voluptatem facilis consequatur ipsum numquam dolorem. Laboriosam maiores dolores consequuntur distinctio.</p><p>Eius accusantium velit placeat ex. Sapiente enim atque enim vitae asperiores earum nostrum. Et adipisci voluptatibus explicabo quo aut accusantium. Delectus voluptas praesentium voluptas sed culpa tempore veritatis.</p><p>Temporibus nostrum libero qui et voluptatem harum architecto. Alias et eum maiores odit fugit esse sequi. Repellat consequatur quia esse impedit quos ea eligendi.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(6,1,3,'Et doloremque iusto et.','commodi-earum-in-optio','Quasi assumenda quas necessitatibus placeat magnam ipsa vitae. Laborum minima consequuntur soluta voluptatem assumenda. Nesciunt occaecati illo dolores et possimus voluptatem.','<p>Neque sunt et ipsam consequuntur saepe eveniet ut. Tempora perferendis facere et minima architecto aperiam quod. Voluptas voluptates optio repellendus et. Necessitatibus in eos iure ex excepturi hic.</p><p>Voluptate dolore quaerat dolorem et. Voluptatem nostrum itaque nemo est dolorem suscipit sed. Ut dolorem commodi sequi mollitia vel odit. Est quis ipsum est sint. Autem vel minus error inventore.</p><p>Occaecati occaecati ab ratione pariatur pariatur eos et. Quia odit aut aut ea maxime. Aperiam nihil sint tenetur numquam magnam vero.</p><p>Similique rerum aut reprehenderit quos iusto natus quibusdam. Consequatur quis fugit perferendis sapiente aliquam aperiam. Asperiores qui voluptatibus non voluptatem id incidunt maxime. Provident nisi rerum qui quas amet. Quia odit ab ut molestiae et.</p><p>Nostrum harum iure nesciunt molestiae. Quia cumque ut repellendus sint. Delectus omnis delectus repellendus ut maiores quos.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(7,1,2,'Et quis tempora beatae.','qui-enim-autem-consequatur-et','Perferendis vitae dolore et debitis deserunt soluta. Occaecati iure occaecati voluptatum vel eum unde. Quae blanditiis perspiciatis quis maiores repellendus.','<p>Sunt odio et reiciendis omnis reprehenderit. Et non cum repellendus reiciendis. Eaque libero aspernatur et nisi commodi esse. Asperiores dignissimos vero et et ea ea dolorem et.</p><p>Sint nobis quo explicabo velit ratione quia est. Maiores animi aut enim. Reiciendis quos saepe sit vel dolorem pariatur et. Est eius rerum autem ratione aut et deleniti ut.</p><p>Quisquam animi ullam dolorum esse recusandae totam delectus. Aut et quod consequatur veritatis nemo ex fugit. Labore id animi nobis esse.</p><p>Ipsum nam occaecati repellat iusto quibusdam. Necessitatibus maxime illum cumque nobis nemo ex. Sit corporis vitae facere maxime fugiat dolores excepturi.</p><p>Nulla commodi dolor delectus. Aut ducimus nobis atque unde. In accusamus consectetur fuga quia.</p><p>Unde sunt repellendus cumque optio. Aliquam impedit eveniet rerum et. Et itaque at porro sit. Dolor et repellat tempore cupiditate architecto qui.</p><p>Quas facere quia quaerat accusantium nihil in rerum. Cumque qui et animi culpa. Molestiae eum non vero molestias occaecati tempora quo. Suscipit voluptatibus debitis laudantium. Libero quasi dolorem ullam voluptatem commodi labore aut earum.</p><p>Tempore commodi esse quia ad et. Ab et corporis modi quia eum. Magni voluptatem similique quaerat et harum odit.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(8,2,2,'Debitis rerum maxime provident quas vitae.','tempora-voluptatem-reprehenderit-nesciunt-consequatur','Molestias non necessitatibus deleniti ipsam. Repellendus perspiciatis dolore est et natus similique dolore. Excepturi voluptatem accusantium facere.','<p>Ut consequatur amet quae et. Eum sed dolor maiores rerum. Et repudiandae sed minima praesentium facilis consequatur.</p><p>Consequatur at dolor laboriosam rem amet sint nihil. Occaecati qui aliquid optio nam qui est. Unde odit ullam repudiandae incidunt optio porro. Explicabo autem repellat fugit quia molestias dolor quas.</p><p>Qui tempore dolor rem molestiae aut. Enim sit neque numquam saepe maxime velit nisi. Aut excepturi rerum voluptate eligendi. Reprehenderit voluptas magnam rem nisi voluptatem animi architecto. Ut illo molestias explicabo sequi dolorum ut qui.</p><p>Nihil est qui blanditiis voluptatem facere aliquid. Aliquam facilis in qui aut non. Sint non saepe dolores quam. Et ducimus officia aut.</p><p>Aut ut adipisci a aut est illo. Cupiditate eum veniam quo ut. Earum aut aut officiis provident. Suscipit deserunt sed et quasi sed.</p><p>Explicabo et ut aut quia sint. Repellat praesentium cum iste corporis. Beatae saepe in qui similique.</p><p>Qui qui possimus magni nam. Omnis eos natus esse sed a dolor. Asperiores aperiam cumque velit impedit eum quaerat.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(9,1,1,'Amet fugit nostrum labore quo vel et sunt velit.','rerum-laboriosam-cumque-alias-debitis-nobis-aut-eum-itaque','Quia sed repellat occaecati id quia animi. Rerum quibusdam voluptatem qui omnis voluptate nihil consequatur. Voluptas modi at laboriosam nobis et ut. Eum officiis et iure voluptatem veritatis est nihil.','<p>Voluptas impedit voluptas rerum illum et harum velit. Voluptas alias eaque illum. Itaque optio ullam odit voluptatem tempore. Eos voluptatem aut ut sed velit dolor rerum.</p><p>Eum qui et nulla qui. Architecto molestias aliquid laudantium tenetur. Possimus ratione impedit suscipit a veniam deleniti dolores. Temporibus alias enim ea maxime odit omnis est.</p><p>Minima perferendis quidem quo consequatur similique maxime dicta. Occaecati quo aut itaque. Eligendi praesentium rerum dolor. Hic odio voluptates voluptatem libero unde.</p><p>Iure autem eveniet in autem. Ut mollitia est cumque. Sed et eius veniam voluptate. Vel tempora sint qui ea aperiam saepe est.</p><p>Maiores quam culpa quam et. At exercitationem dolorum tempora quo sunt non voluptate beatae. Sunt sit eaque blanditiis quasi.</p><p>Et in unde omnis architecto. Vel inventore minus suscipit. Ea velit neque eligendi qui aspernatur nulla.</p><p>Porro quis ducimus et. Necessitatibus maiores iusto ab nemo similique non recusandae corrupti. Et et quis veniam voluptas quae doloribus. Consequuntur sint magni voluptas ea est.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(10,1,1,'Non esse consequatur accusamus corrupti cum odio.','ullam-nesciunt-voluptatem-aut-ipsam','Laudantium laudantium nisi sed quia aut. Quasi rem vero assumenda facilis quos alias est eum. Non labore maxime qui esse repellendus explicabo. Blanditiis est et ipsa magni molestias deserunt. Nulla et voluptas quibusdam consequatur perspiciatis.','<p>Voluptates aspernatur aut magnam iure odio. Aut odit quo sit aliquam nihil. Est eos alias modi quo quod. Et iusto qui aut sequi.</p><p>Et harum sit nesciunt enim. Minus aspernatur dolore autem. Dolorum eum doloremque fugit vero labore sit occaecati.</p><p>Culpa aut expedita debitis nostrum minus ratione quos. Eos rem ipsum iste itaque. Perspiciatis cupiditate eius doloremque optio aspernatur voluptatem.</p><p>Vitae et quo totam expedita perferendis illo. Vitae dignissimos vel non aut earum et ea. Hic ab aspernatur rerum assumenda. Et numquam non enim dolores dolor itaque.</p><p>Doloribus quia est odit deserunt aliquid quibusdam. Recusandae ea qui velit consequatur quas. Suscipit sed possimus delectus optio modi eaque rerum.</p><p>Vel nemo tenetur non expedita sit. Beatae sapiente sit voluptatum aut velit molestias nostrum. Est eligendi autem cumque minima et.</p><p>Occaecati et esse recusandae velit praesentium eveniet accusantium. Sint quia ea rerum et quae commodi illum. Voluptatem vel libero et quo commodi et.</p><p>Dolorum repudiandae maxime nostrum. Et iusto dignissimos optio omnis blanditiis. Ut est eaque reiciendis accusantium tempore unde. Ipsam sint fugit ut et.</p><p>Labore ut et ea cumque debitis. Omnis sit ipsum accusantium veritatis adipisci reiciendis. Sint maiores autem distinctio animi. Iusto tenetur quia minima dolores.</p><p>Consectetur consequatur voluptatem odio dolor fugiat qui. Laboriosam eligendi sunt illo omnis. Neque quidem aliquid quasi aut maxime id voluptates eum.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(11,2,1,'Est odio nemo aut deleniti natus.','aut-nihil-consequatur-aut-necessitatibus-repellendus-magnam-non','Minus cum eveniet qui. Maiores dolor quia ad consequuntur temporibus repellat. Eos sit voluptas quibusdam officiis. Occaecati soluta quia totam aspernatur enim tempore magni.','<p>Repellat sed distinctio itaque officia id mollitia. Dolore ipsa nulla vero. Quia iure veritatis deserunt exercitationem. Sapiente pariatur et sed a non recusandae non.</p><p>Minima fuga ea similique non reiciendis et. Dignissimos libero tenetur ea. Corrupti labore placeat dicta ratione.</p><p>Laboriosam reiciendis ipsam sit facilis hic ea excepturi. Non at autem quos maxime qui ducimus sint.</p><p>Dicta dolor enim deserunt ut. Sit voluptas nisi aut minus mollitia esse mollitia. Praesentium qui laboriosam impedit commodi nulla eius voluptate. Sit in voluptatum voluptatum dolores qui.</p><p>Eligendi et corporis porro quaerat voluptas corrupti omnis. Cupiditate nostrum enim suscipit et. Natus maiores rem a autem odit quidem.</p><p>Et et amet iusto ullam sunt hic odio. Et facere et inventore rerum omnis modi eos dignissimos. Ut fugit eveniet architecto cum minus officia. Et omnis perspiciatis perspiciatis atque necessitatibus eos quibusdam quaerat.</p><p>Assumenda facilis ut deserunt ad. Corrupti saepe explicabo autem et et. Perferendis et iusto suscipit occaecati reiciendis id sed quis.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(12,1,1,'Optio qui reiciendis veniam.','nobis-architecto-ipsa-aut-maxime-est','Cupiditate reiciendis omnis placeat velit. Hic ut quas suscipit et. Sed aperiam neque aut mollitia non sunt. Vel in eligendi eos fugit magnam.','<p>Reprehenderit dolore ea rerum voluptas animi veritatis harum. Consequatur harum dolores illo adipisci exercitationem facere ducimus consectetur. Tempore assumenda placeat reprehenderit voluptatibus inventore impedit quod.</p><p>Molestiae natus aut provident. Et optio ipsum ut modi ullam aut ex. Quia explicabo nemo rerum atque. Ex dolores ut enim et mollitia.</p><p>Laboriosam praesentium quia soluta qui dolor voluptatibus qui. Asperiores doloribus accusamus nihil dolorum in voluptatem ullam nemo. Molestias et et consequatur est et. Vero eum est odit.</p><p>Est et tempore accusantium id ab fuga. Quod quis veritatis iusto non.</p><p>Doloribus voluptatem alias quas amet. Debitis incidunt vero magnam et et consequuntur. Nesciunt nihil eveniet culpa dignissimos odit.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(13,1,2,'Nesciunt natus quis exercitationem omnis vel minus et.','voluptas-ad-libero-qui','Sit nulla vero accusantium velit illo harum tempore. Alias consequatur cum assumenda et molestiae ipsum aliquam. Distinctio rerum fugiat temporibus deserunt omnis. Neque sequi minima vero quas adipisci repellendus adipisci.','<p>Ea mollitia error eius quod quo laborum quo. Molestiae corporis aperiam est aliquam officiis id. Dolores aut incidunt est laudantium libero et. Et qui et reiciendis quibusdam.</p><p>Sunt voluptas nemo laboriosam quia officia. Blanditiis aut accusantium magnam explicabo. Sit magnam hic aperiam placeat. Impedit consectetur sunt cumque eius repellat error maxime.</p><p>Id aperiam quisquam doloremque laboriosam in. Corrupti laborum officia officiis rerum sequi in. Fugiat iusto cumque dolor sapiente sit dolores nobis. Et sit nobis et eius est enim repellendus.</p><p>Doloribus ut ut voluptatibus vel omnis voluptate. Nesciunt veritatis et qui quasi maiores. Dolorum pariatur vel mollitia dolor beatae vero adipisci. Error repudiandae doloribus qui reprehenderit.</p><p>Nihil illo qui laborum ab velit pariatur. Eius quis nam itaque quo. Facilis quidem nostrum quae reprehenderit qui cumque nobis. Saepe placeat velit neque.</p><p>Voluptatum omnis id vel tempore quam libero. Corrupti recusandae est iure nemo natus. Quaerat quia aspernatur voluptas maxime est voluptas.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(14,2,2,'Architecto et voluptatem tempore voluptatem laudantium quaerat.','provident-accusamus-nemo-sed-ut-quis-quidem-non','Aut quos qui magnam corrupti. Expedita eum perspiciatis id culpa aut iusto soluta. Id ad a totam consequatur et ut.','<p>Autem ut quia rerum eos. Aut quasi sed sint asperiores. Molestiae atque odio odio consequatur porro veritatis. Odit maiores itaque sunt velit sit impedit consequatur.</p><p>Voluptas maiores eius praesentium mollitia. Officia sit voluptatem voluptate. Eum quaerat sapiente tenetur in sit autem reiciendis. Sed et qui quidem nulla excepturi sed culpa.</p><p>Id assumenda qui quia aut minima. Facilis in et est ipsa harum sed quis. Accusamus omnis temporibus sint quis. Quam corrupti dolorum sint soluta porro pariatur voluptas id.</p><p>Eos aut voluptatem corrupti illum delectus. Dolorem est dolor rerum in laudantium. At repellat impedit et excepturi. Quia rerum id voluptate doloribus.</p><p>Quia quis alias et possimus. Est suscipit iure beatae velit. Magnam et laborum earum. Laborum nam eius mollitia quod autem.</p><p>Fugit qui eum nisi voluptas. Itaque nihil cum tempore consequuntur. Vitae et vero earum suscipit fugit aspernatur.</p><p>Laudantium perspiciatis placeat fuga non omnis doloribus. Sed amet cupiditate quisquam dolorum harum. Sint iste reprehenderit est nam ea sapiente.</p><p>Eos ipsum qui molestiae veritatis et est. Et consequatur tenetur eius est modi. Enim quo officia provident qui quia.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(15,2,2,'Voluptatem dolorem ex.','laudantium-occaecati-id-magni-nesciunt-et-quasi-praesentium','Aliquam nulla explicabo aspernatur a quo. Sunt dolorem aliquam excepturi pariatur ut.','<p>Sequi enim recusandae earum voluptatem facere libero non ea. Soluta officia repellendus a commodi iure. Beatae molestias provident reiciendis consequatur hic autem placeat nobis. Nostrum laudantium explicabo sed aut laboriosam.</p><p>Dignissimos iure eos ratione quidem. Et explicabo labore est debitis vel nobis. Laudantium at omnis et perspiciatis architecto blanditiis. Laudantium vitae accusantium non dolor et.</p><p>Sit est temporibus et sit. Est veritatis non alias corporis vitae voluptates. Dolorum qui perspiciatis et et.</p><p>Iusto qui non iure harum. Consequuntur aliquid nisi excepturi voluptatem recusandae. Eos corrupti et voluptas.</p><p>Necessitatibus id minus repudiandae quo aut et et. Qui voluptate enim et. Odit iste fuga amet omnis qui ut. Rerum sint et libero eius quibusdam expedita voluptatibus.</p><p>Ipsa libero animi hic dolores. Culpa est aliquam porro debitis et. Voluptatem minima nostrum officia doloribus quia nesciunt esse.</p><p>Tenetur autem molestias culpa nihil esse ut optio. Est quis aut atque aut ad mollitia minus velit. Harum quia aut consequuntur dolores sunt ut earum.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(16,1,2,'Est facilis libero animi in aut ut.','ab-sit-ut-molestiae','Veritatis itaque eum consequuntur minima. Sit consectetur commodi inventore magnam porro labore pariatur. Perspiciatis suscipit id consequuntur voluptatum velit.','<p>Qui voluptas nulla sint. Quod cum nihil optio et ex. Nesciunt doloribus quia quam dolores.</p><p>Accusamus ipsum architecto maxime tenetur. Iste est laudantium ipsum occaecati. Optio aperiam quas commodi sequi facilis magni et.</p><p>Eligendi sint unde maiores eos. Fugit temporibus necessitatibus est occaecati velit dolores et. Nemo quia ut hic dolores recusandae. Et eligendi officiis et veritatis voluptatem maiores quia at.</p><p>Odit quis dolor consectetur nulla ut voluptas. Est eligendi quia laborum est quia error aliquid. Et itaque at natus sapiente quasi quod.</p><p>Nam voluptatem aut eum. Voluptatem commodi enim provident omnis sit qui maxime. Rerum consequatur vero magnam molestiae laudantium.</p><p>Corporis mollitia temporibus exercitationem id non libero perferendis. Qui autem error eligendi aut impedit rerum qui. Praesentium optio accusantium voluptas voluptatem consequatur quisquam dolor aut.</p><p>Sed optio laudantium in recusandae asperiores qui qui repudiandae. Laudantium id delectus porro aspernatur adipisci.</p><p>Placeat est mollitia sint fugiat reiciendis. In est minus cupiditate aperiam. Qui temporibus placeat perspiciatis.</p><p>Error eum quo voluptatibus doloremque expedita id. Facilis sed dolor a et incidunt consequatur. Et et odit repellendus laudantium et.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(17,2,3,'Fuga repellendus est voluptatum accusantium incidunt.','voluptatem-iste-itaque-sunt-molestiae-sed','Ut eius laboriosam earum aliquid facilis ipsum ea perferendis. Ullam est similique a dolor aut. Nihil maxime nihil maiores quia laborum perspiciatis aut.','<p>Alias molestiae consequatur minima illo est placeat. Et eum ipsa alias nobis sit vitae eius. Omnis incidunt tenetur dolores perspiciatis culpa alias. Sint dolorum molestias officiis sed.</p><p>Et quaerat quisquam omnis laboriosam. Sint omnis quia beatae nostrum nihil in aut placeat. Debitis porro perferendis voluptatem enim aperiam.</p><p>Amet odio rerum qui ad. Voluptatem aut praesentium veritatis maxime ut vel nihil.</p><p>Est nostrum consequuntur quia in vero aut mollitia. Ad ut voluptatem mollitia quis vero fuga. Doloribus temporibus eos officia quos placeat hic. Possimus quae quia ut.</p><p>Soluta sunt et veritatis minima quia quis. Rerum eum veniam et. Impedit provident minus quod quia eius in modi earum.</p><p>Animi ullam officia cumque. Enim iste distinctio porro. Reiciendis non sint recusandae dolorum autem tempore nihil. Libero vitae eius aspernatur vel quas molestias.</p><p>Mollitia qui dolor dignissimos porro repudiandae odio voluptas ut. Reiciendis eum iusto omnis. Minima non velit esse impedit est dignissimos ea veniam.</p><p>Soluta earum nam est voluptatibus est animi totam. Aut repellat qui laborum quam sint omnis nostrum. Est alias aliquam quod asperiores. Occaecati velit itaque nesciunt.</p><p>Assumenda facilis dolor occaecati omnis magni voluptatum. Aut quidem facilis officia alias nihil molestias id. Architecto numquam mollitia et id repellat. Quae non aut nihil.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(18,2,1,'Commodi velit enim architecto.','perspiciatis-quasi-et-asperiores-dolore-commodi','Eum sequi culpa neque autem. Occaecati sit vero numquam et aliquam qui. Itaque odio iste magni. Ducimus sit rerum autem nihil iste corporis aperiam.','<p>Rerum fugiat voluptatem est ut inventore. Atque voluptatem cumque blanditiis soluta. Sapiente voluptates perferendis autem nihil quas iusto dolor harum. Reiciendis ipsum odit aut aut esse dolore. Ut nulla cum et hic ullam et.</p><p>Dolorem ipsum vel nulla rem. Excepturi dolorum rerum deleniti in corporis. Aut veniam esse qui animi at qui. Distinctio odit veniam est ipsum maiores repudiandae. Atque qui dolorem tenetur perferendis rem aut.</p><p>Ut velit animi ut incidunt molestiae doloribus possimus. Eos necessitatibus aut itaque vel. Minima ipsam sed inventore sit maiores voluptates cumque atque.</p><p>Doloribus et et harum aliquid dolores. Amet perspiciatis et qui quia sed sit corrupti.</p><p>Exercitationem sint molestias provident. Facilis sed cumque omnis quibusdam. Pariatur in et dolore.</p><p>Aut explicabo velit omnis est voluptatem. Consequuntur sunt mollitia molestias sit in rerum. Accusantium et vel id velit delectus sed neque sunt. Ducimus sed magnam consequatur quia aut mollitia.</p><p>Ad doloribus sunt id atque. Cumque nihil nemo nemo quod est. Excepturi qui ducimus qui similique.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(19,1,2,'Vel sit omnis.','unde-ea-et-et-rerum-ut','Sit magnam dolor eius dicta ipsa numquam. Reiciendis incidunt accusantium omnis eos quas ipsa quisquam. Ea eveniet architecto esse minus provident.','<p>Ut dolor aut quo. Nobis aliquam voluptatum aut. Ut architecto praesentium animi nostrum quas. Voluptas dolores et deserunt odio eligendi culpa.</p><p>Fuga officiis rerum sed voluptatem in. Voluptas in aut itaque minima dignissimos provident dolores. Possimus fuga aspernatur unde debitis reiciendis ea.</p><p>Voluptates harum minus vel voluptatibus adipisci placeat. Dicta inventore omnis neque architecto adipisci voluptatem aut accusamus. Quidem quisquam tenetur commodi asperiores eos quia.</p><p>Distinctio est soluta laudantium facere sed. Quis sunt laborum totam quia. Modi cum reprehenderit quia eligendi hic.</p><p>Ab voluptatem id quae sit beatae expedita. Tenetur beatae laboriosam voluptates eveniet. Dolor temporibus fugit atque aliquam quasi enim culpa sequi. Natus ut molestias earum perferendis accusamus pariatur quasi.</p><p>Nam omnis ab rerum. Sit non reprehenderit et sed quo. Dolorem velit sit labore non facilis.</p><p>Maxime similique non iste sit veniam alias tempora. Minima fuga omnis ut nulla hic enim. Odio est voluptatem molestiae sed.</p><p>Voluptates minus aut quia minus possimus ea temporibus. Nisi non quidem illo. Maxime dolorem voluptates velit veritatis quia.</p><p>Sit quo aut quam molestiae optio voluptatum alias voluptas. Quia provident explicabo ullam quia. Nemo qui tenetur ipsa eum.</p><p>Sed eum necessitatibus vero eveniet qui velit omnis. Et qui assumenda quos cumque consequatur cumque. Eius assumenda voluptate molestiae quidem quis quas.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19'),
(20,1,1,'Natus fugit sequi eum dolor quia laborum consequatur.','ducimus-provident-autem-necessitatibus-earum-aliquam-fuga-eum','Tenetur maiores quae enim vel et non quod. Debitis ea qui ut quis animi architecto. Asperiores praesentium dolor iure accusantium non iste.','<p>Aliquam aut totam qui ipsa beatae. Ipsum hic ipsa dolorem voluptas aperiam pariatur quae. Et illo aliquam in facere. Alias eum itaque reiciendis debitis qui quis.</p><p>Libero nesciunt ut optio doloribus voluptatem. Explicabo quis eos corrupti voluptatem.</p><p>Voluptate saepe vel non repellendus cumque. Cum dicta labore dolor et eaque quia. Quaerat blanditiis inventore dolorum occaecati ipsum voluptatem.</p><p>Similique qui cumque dolorem explicabo nobis. Aut et sit consequatur natus tenetur. Et repellat omnis unde. Animi libero quam inventore possimus ullam deserunt.</p><p>Voluptatum nesciunt nesciunt et recusandae ea. Nostrum earum rerum praesentium hic earum.</p>',NULL,'2021-10-08 13:14:19','2021-10-08 13:14:19');

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_username_unique` (`username`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

/*Data for the table `users` */

insert  into `users`(`id`,`name`,`username`,`email`,`email_verified_at`,`password`,`remember_token`,`created_at`,`updated_at`) values 
(1,'Empluk Nainggolan','widya.mangunsong','heru44@gmail.com','2021-10-08 13:14:18','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi','9ggkxoL3FI','2021-10-08 13:14:18','2021-10-08 13:14:18'),
(2,'Zelda Michelle Wastuti','ranggraini','betania.widiastuti@gmail.com','2021-10-08 13:14:18','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi','CCiKxnRNCU','2021-10-08 13:14:18','2021-10-08 13:14:18'),
(3,'Raisa Pertiwi','padma.mansur','calista83@gmail.com','2021-10-08 13:14:18','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi','Sh8aujOZ4cxIkZWrGDpeCLuKJZCr19nZdwfzn0Rqew49xoKoANnJ5kMOnypM','2021-10-08 13:14:18','2021-10-08 13:14:18'),
(8,'Muhammad Padhilah','padhilahm','padhilahm@gmail.com',NULL,'$2y$10$dE1ve8KyASBe.9/ir/.iou5JTx7iv0CSdA1EJilAxBitAuK36kyum',NULL,'2021-10-09 14:32:17','2021-10-09 14:32:17');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
